### ISSUE TITLE
(feature idea) Cleave/Hitstop modifier 

### ISSUE THREAD

**Issue by PolehammerSupremacy** [Chiv2-Community/polehammer.net#14]
a drop down menu that applies a damage multiplier of 1x, 2x, 3x, 4x, 5x for all weapon types' Heavy attacks and Chop/Cut type Light attacks. (Blunt does not cleave on Light attacks - has hit stop - only ever gets 1x on Light attacks)

**Comment by Jacoby6000** [comment]
This is done
