### ISSUE TITLE
Move the base fork to Chiv2-Community

### ISSUE THREAD

**Issue by Jacoby6000** [Chiv2-Community/polehammer.net#32]
Seems I don't have access to do this, so you'll need to.  I invited you to the community.

**Comment by aardvarkk** [comment]
@Jacoby6000 No worries -- the Chiv2-Community one is now ahead of my repo by a fair number of commits. I don't think it makes too much of a difference so maybe we'll just leave it as-is for the time being.

**Comment by Jacoby6000** [comment]
Some people have started trying to contribute, and the base fork being separate from primary development has caused a little bit of confusion. I can submit another PR for sync if necessary. Nothing should be in conflict

**Comment by aardvarkk** [comment]
@Jacoby6000 Should be done now!

**Comment by Jacoby6000** [comment]
Awesome, thank you!
