### ISSUE TITLE
Filter weapons based on certain characteristics

### ISSUE THREAD

**Issue by aardvarkk** [Chiv2-Community/polehammer.net#6]
Perhaps above the weapon "Search" box there could be various little tags that could be enabled/disabled to reduce which weapons show in the Search dropdown. Examples:

- 1H & 2H weapons
- Damage Type (Cut, Chop, Blunt)
- Which class can wield the weapon (Officer, Raider, etc.)

**Comment by Jacoby6000** [comment]
This is complete, may need some TLC to make it a better UX, but for now it works.
