### ISSUE TITLE
Add Damage category for Thrown Damage

### ISSUE THREAD

**Issue by aardvarkk** [Chiv2-Community/polehammer.net#8]
- Do we care about splitting into damage to various body parts?

**Comment by Jacoby6000** [comment]
This is complete.  Currently each thrown-damage category (head, legs, torso) is encoded separately in the model.  Today I realized head damage is +25% of torso damage, legs are -25%.  We should be able to condense the model here.  There's some unanswered questions around how normalization should work; if thrown damage should be normalized with melee damage.
